"""Initial migration.

Revision ID: da285ad23022
Revises: 
Create Date: 2024-07-25 14:35:39.708722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da285ad23022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('waist', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('activity_level', sa.String(length=50), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('activity_level')
        batch_op.drop_column('waist')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('gender')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
